FROM arm64v8/python:alpine3.19

LABEL maintainer="Awhitedress"

ENV TZ=Asia/Shanghai LANG=zh_CN.UTF-8 PYTHONUNBUFFERED=1

EXPOSE 8000

WORKDIR /usr/src/myapp

COPY . /usr/src/myapp/

RUN python3 -m pip install --no-cache-dir requests colorlog aiohttp -q

ENTRYPOINT ["python3"]
CMD ["main.py"]